"""add last_viewed_at

Revision ID: 1d483cd21224
Revises: ecc792cb829e
Create Date: 2026-02-12 21:36:55.127354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d483cd21224'
down_revision: Union[str, Sequence[str], None] = 'ecc792cb829e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'last_viewed_at')
    # ### end Alembic commands ###
