"""add view_count and playback_position

Revision ID: ecc792cb829e
Revises: a6051d6de0e1
Create Date: 2026-02-12 21:13:47.313992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc792cb829e'
down_revision: Union[str, Sequence[str], None] = 'a6051d6de0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('view_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('content_items', sa.Column('playback_position', sa.Integer(), server_default='0', nullable=True))
    op.add_column('content_items', sa.Column('last_played_at', sa.DateTime(), nullable=True))
    # 将已有行的 NULL 填充为 0
    op.execute('UPDATE content_items SET view_count = 0 WHERE view_count IS NULL')
    op.execute('UPDATE content_items SET playback_position = 0 WHERE playback_position IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'last_played_at')
    op.drop_column('content_items', 'playback_position')
    op.drop_column('content_items', 'view_count')
    # ### end Alembic commands ###
